Update AdaptiveRetryStrategy.h
Fixes compile error:

AdaptiveRetryStrategy.cpp:80:34: error: absolute value function 'abs' given an argument of type 'long long' but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]

the `abs` function with long long parameter is defined in the `cstdlib` header as of C++11